title: The Nextus
description: >-
  A mockup and playground for the next redesign of The Nexus.

markdown: kramdown

kramdown:
  # use Github Flavored Markdown
  input: GFM
  auto_ids: true
  # do not replace newlines by <br>s
  hard_wrap: false
  toc_levels: 1..3

url: 'https://thenexustv.github.io'
baseurl: '/nextus'

exclude:
- README.md
- .gitignore
- Gemfile
- Gemfile.lock
- .sass-cache
- CNAME
- LICENSE
- vendor

sass:
  style: compressed